### ISSUE TITLE
pigpio not working after recent hassio-update

### ISSUE THREAD

**Issue by Beiri22** [Poeschl/Hassio-Addons#178]
**Which addon?**
pigpio 1.1.1 and 1.1.0

**Describe the bug**
Does not work. Error in log (over and over again):
```
[01:01:16] INFO: Started pigpio
2021-02-10 01:01:16 myCreatePipe: Can't set permissions (434) for /dev/pigpio, No such file or directory
2021-02-10 01:01:16 pthFifoThread: fopen /dev/pigpio failed(No such file or directory)
chmod /dev/pigerr failed (No such file or directory)
```

**To Reproduce**
Look into the log.

**Expected behavior**
Should control my pins.

**System**
* Supervisor version: supervisor-2021.02.6
* Host system version: Home Assistant OS 5.11
* Core: core-2021.2.2
* on Pi 4

**Comment by an124pilot** [comment]
I have the same issue. Within the home-assistant.log, it shows for the Pigpio the message below. Any suggestions on a fix?

`2021-02-09 20:21:46 ERROR (MainThread) [homeassistant.components.light] Error while setting up rpi_gpio_pwm platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/rpi_gpio_pwm/light.py", line 82, in setup_platform
    driver = GpioDriver(pins, **opt_args)
  File "/usr/local/lib/python3.8/site-packages/pwmled/driver/gpio.py", line 25, in __init__
    raise ConnectionError('Could not connect to the pigpio daemon')
ConnectionError: Could not connect to the pigpio daemon`


**To Reproduce**
Look into the log.

**Expected behavior**
Should control my pins.

**System**

Supervisor version: supervisor-2021.02.6
Host system version: Home Assistant OS 5.11
Core: core-2021.2.2
on Pi 3 B+

**Comment by Poeschl** [comment]
Hassio changed the way how addons can access die devices of the host system. I don't see a quick fix, unfortunately. I will look into it this evening.

**Comment by Poeschl** [comment]
Opened [issue on supervisor](https://github.com/home-assistant/supervisor/issues/2558).

**Comment by phcella** [comment]
Hello, same problem here

**Comment by JyrkiSuominen** [comment]
Hi, totally same problem here.

 It would be very good to have this pigpio operative again. It worked few days and then crashed.

**Comment by Poeschl** [comment]
This issue depends on the linked supervisor issue above. Without it solved pigpio won't again.

If you want, go there an give the [issue](https://github.com/home-assistant/supervisor/issues/2558) an thumbs up, to show its also affecting you.

**Comment by Beiri22** [comment]
@Poeschl: I see that you are using git clone and compile to build pigpio. What about the following:
Couldn't we create a patch file for pigpio that replaces the fixed /dev/-paths to a different location -- and then compile the patched version. It might be only a few locations of the source that need to be changed!

**Comment by Beiri22** [comment]
You could run:
```Dockerfile
RUN git clone 'https://github.com/joan2937/pigpio.git' -b v78 /pigpio && cd /pigpio
RUN find -type f -exec sed -i -re "s#/dev/pig(pio|out|err)#/tmp/pig\1#g" {} \;
RUN make  && make install
```

**Comment by Poeschl** [comment]
@Beiri22 Great idea, I will try that to get it working again.

**Comment by Poeschl** [comment]
@Beiri22 please cross-check version 1.2.0 which gets build right now. 😉 Please close the issue when the addon works normally.

**Comment by Beiri22** [comment]
I will check it. By now there is no update notification, yet.

**Comment by Beiri22** [comment]
So. The error messages have vanished. The plugin does start successfully. As far as my issue concerns everything works as intended. Thank you.

**Comment by an124pilot** [comment]
Thank you so much @Poeschl and @Beiri22  for fixing this. Very much appreciate it.

**Comment by rickardnr1** [comment]
agree with an124pilot. well done fix pigpio!almost cant live without it ;)
