### ISSUE TITLE
Mopidy Youtube not working

### ISSUE THREAD

**Issue by Poeschl** [Poeschl/Hassio-Addons#22]
**Which addon?**
Mopidy

**Describe the bug**
The youtube integration is not working at all.

**To Reproduce**
1. Go to 'Search'
2. Type: `yt:https://www.youtube.com/watch?v=eKFTSSKCzWA`
3. Error is shown (should be playing the audio)

Right now the official plugin is installed, it might be worth to look at this fork: https://github.com/natumbri/mopidy-youtube/issues/27

**Comment by natumbri** [comment]
Hi @Poeschl - let me know how you go, if you try my fork.

**Comment by Poeschl** [comment]
Hi @natumbri, I will. 😉 
Which of your branches contains the latest code?

**Comment by natumbri** [comment]
Hi - I squashed everything down into develop last night, so that's the one to use.  BUT, I forgot to fix one thing up - the location for certain cache files is hard-coded (/var/cache/mopidy/ I think) instead of referring to modipy.conf. The plug-in works, but may cause permission problems. I will fix asap.

**Comment by Poeschl** [comment]
Take your time. If I find some time to code it will be Sunday 😅

**Comment by natumbri** [comment]
Should be fixed now.
