### ISSUE TITLE
ICantBelieveItsNotValetudo Fork with support for mutliple robots

### ISSUE THREAD

**Issue by derrohrbach** [Poeschl/Hassio-Addons#283]
**Which addon?**
ICantBelieveItsNotValetudo

**Is your feature request related to a problem? Please describe.**
Running multiple instances for multiple robots

**Describe the solution you'd like**
I implemented a fork of ICantBelieveItsNotValetudo which supports mutliple configs for people with multiple robots. I'd like to talk about how and if we should work together to get it into this repo and solve multiple robots forever. Sadly Hypfer did not accept my PR into mainline ICantBelieveItsNotValetudo, so it'll have to stay a fork. The question is do you want to include it or do we just continue to use workarounds like my other fork of this addon repo which adds a second instance of the app.

**Describe alternatives you've considered**

I developed a fork of this addon repo, which just includes a second instance of ICantBelieveItsNotValetudo
https://github.com/derrohrbach/Hassio-Addons
--> I think this is a workaround and discoverability for other users is bad!

I developed a fork of ICantBelieveItsNotValetudo which supports multiple configs
https://github.com/derrohrbach/ICantBelieveItsNotValetudo
--> Was sadly not accepted: https://github.com/Hypfer/ICantBelieveItsNotValetudo/pull/76

This is also related to:
https://github.com/Poeschl/Hassio-Addons/issues/271

**Comment by Poeschl** [comment]
I wouldn't name your fork of Valetudo a workaround. Since it will not get merged into ICBINV it becomes a separate, specialized project.
For myself I don't see the need to include it in my collection. Nevertheless feel free to make an own addon repository which contains your multi instance build.

I thought a few times about just starting a few instances of ICBINV inside of one addon, but the configuration was is not possible because auf the yaml config nesting limit of HA.
