### ISSUE TITLE
HA Syncthing Integration

### ISSUE THREAD

**Issue by Axydas** [Poeschl/Hassio-Addons#324]
Hi

i install the Syncthing addon. I start it normally and i am trying to connect it with Home Assistant integration. I add the local URL and the API key in the token field and i am getting the below error:
![image](https://user-images.githubusercontent.com/79807389/179679140-3d6bfbd3-693d-4656-95e3-574dd157c0b3.png)

Anyone who can help?

**Comment by Poeschl** [comment]
When syncthing is run via the Addon its Web-Interface is not accessible on localhost per default. Its is availables via the address  `http://243ffc37-syncthing:8384` from inside the Home Assistant host. So try this as URL.

Otherwise you might try to configure the web interface port on the addon configuration.

**Comment by Axydas** [comment]
> When syncthing is run via the Addon its Web-Interface is not accessible on localhost per default. Its is availables via the address `http://243ffc37-syncthing:8384` from inside the Home Assistant host. So try this as URL.
> 
> Otherwise you might try to configure the web interface port on the addon configuration.

Thanks a lot. It is ok now
