### ISSUE TITLE
Don't know how to sync /config and /backup now with the Syncthing addon.

### ISSUE THREAD

**Issue by jwinston100** [Poeschl/Hassio-Addons#460]
I understand there have been changes to this addon due to changes in HA, and I looked through the various issues, but I cannot figure out now how to sync my /config and /backup folders like before. The previous synced folders now sync to the same names under /addon_configs/XXXXXXXX_syncthing/ instead of /. How do I tell the new Syncthing add on to map the folders off the root directory? Thanks.

**Comment by Poeschl** [comment]
Can you help me out here @salim-b?

**Comment by salim-b** [comment]
Hi @jwinston100 

The recent refactoring you mention is outlined in https://github.com/Poeschl/Hassio-Addons/pull/450.

Nothing has changed with the `backup` directory, it's still available to Synthing at `/backup`, same as before.

But if you used to sync the `/config` directory, this won't work anymore, since we don't mount HA's `config` directory anymore, but the more modern [`addon_config`](https://developers.home-assistant.io/blog/2023/11/06/public-addon-config/) instead, which makes Syncthing's *own* config available at `/config`, but none of the other HA config files.

We *could* also mount [`all_addon_configs` and `homeassistant_config`](https://developers.home-assistant.io/blog/2023/11/06/public-addon-config/#new-addon_configs-folder), which would make the entire HA add-ons config available at `/addon_configs` and Home Assistant's own config available at `/homeassistant` to Syncthing. But honestly, I don't really see the use case to sync HA's config via Syncthing, there are [better ways to edit config files](https://github.com/Poeschl/Hassio-Addons/pull/450#issuecomment-1874558262). Do you think you otherwise? If so, you might wanna chip in on https://github.com/Poeschl/Hassio-Addons/issues/458.

**Comment by jwinston100** [comment]
I often edit my configuration.yaml, automations.yaml, scripts.yaml, etc. on my own computer which used to use Syncthing to synchronize my computer and my HA device. Is there any way to regain that functionality? Should I try to use an older version of the Syncthing addon? Thank you.

**Comment by salim-b** [comment]
> Is there any way to regain that functionality? Should I try to use an older version of the Syncthing addon?

Yes, you could switch back to v1.17.0 of the add-on, if you want.

We could certainly expose `all_addon_configs` and `homeassistant_config` to Syncthing in the future if there's user demand. I've added a [comment](https://github.com/Poeschl/Hassio-Addons/issues/458#issuecomment-1891075060) to https://github.com/Poeschl/Hassio-Addons/issues/458.

**Comment by jwinston100** [comment]
Thank you. I did revert the version to 1.17.0, and it is working as before now. I've turned off the auto-update feature as well. I'll add a comment there for my two cents and close this.

**Comment by NODeeJay** [comment]
Sadly, I also had to revert, the main point was to sync the esphome folder.
