### ISSUE TITLE
[valetudo mapper] support more than one vacuum instance

### ISSUE THREAD

**Issue by hillbicks** [Poeschl/Hassio-Addons#62]
**Which addon?**
valetudo mapper

**Is your feature request related to a problem? Please describe.**
Maybe this is possible and I just haven't figured it out. I want to draw maps for the roborock instances that I own. From what I understand the current config for valetudo mapper only allows for one instance. 

**Describe the solution you'd like**
Draw maps for all roborock instances that I have. 

**Describe alternatives you've considered**
Setting up an instance for each roborock

**Additional context**
Like I said above. I have two roborocks currently and I want to draw the map for both of them and I'm not sure how to achieve that. If it's already possible, it would be great to get a hint on how to achieve that. I already tried duplicating the entries in config.json for the valetudo mapper, but that doesn't seem to work. So I would be grateful to get a hint as to how to acheive this. Thanks :)

**Comment by Poeschl** [comment]
Since the containing valetudo-mapper application in the Addon only supports one roborock instance at a time its not possible without some tweaks. Nevertheless starting two separated instances should work.
To test it copy the contents of the `valetudo-mapper` inside your `/addons` folder ([like an development addon](https://developers.home-assistant.io/docs/hassio_addon_testing)). Install it over the home assistant core ui and your should have two instances of the  Valetudo-Mapper addon running.
